#!/bin/bash

clingo --mode=clingo ~/Asprilo/benchmark-tool/benchmarks/assign/currentInst/* ~/Asprilo/benchmark-tool/benchmarks/assign/m/encoding.ilp ~/Asprilo/benchmark-tool/benchmarks/assign/control-m/control.ilp $@
