#!/bin/bash

clingo --mode=clingo ~/Asprilo/benchmark-tool/benchmarks/assign/testInst/x100_y37.lp  ~/Asprilo/benchmark-tool/benchmarks/assign/m/encoding.lp ~/Asprilo/benchmark-tool/benchmarks/assign/control-m/control.lp -c horizon=3 $@
